### ISSUE TITLE
Missing English fallback for other languages.

### ISSUE THREAD

**Issue by not-nocturnal** [Priscillalala/FreeSkillSaturday#2]
When playing in a language other than English, item names/descriptions show up as variable names. It would be good if English was used as a fallback. This way anyone who prefers to play in another language can still potentially read the text if they understand some English, instead of being locked out of it completely.

![image](https://github.com/Priscillalala/FreeSkillSaturday/assets/8378762/9b0959f8-4c44-4ef9-98fb-ea4c58462016)

**Comment by Priscillalala** [comment]
Should be fixed in 1.7.0!
